baseURL = 'https://blog.boot.dev/'
languageCode = 'en-us'
title = 'The Boot.dev Blog'
disqusShortname = ""
ignoreFiles = []
footnotereturnlinkcontents = "â†©"
paginate = 10
enableRobotsTXT = true
summaryLength = 15

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'

[taxonomies]
  category = "categories"

[permalinks]
  post = "/:section/:slug/"
  categories = "/:slug/"

[params]
  description = "You don't need a CS degree to get hired, but you do need computer science skills. Prepare to land an entry-level role in tech by building real coding projects."
  footer = "&copy; [Boot.dev](https://boot.dev) {Year}"
  googleTagManager = "GTM-PT7FHFB"
  dofollows = [
    "https://boot.dev",
    "https://blog.boot.dev",
    "https://wagslane.dev"
  ]


[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineAnchors = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'categories'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
