baseURL = 'https://blog.boot.dev/'
languageCode = 'en-us'
title = 'Boot.dev Blog'
disqusShortname = ""
ignoreFiles = []
paginate = 25
enableRobotsTXT = true
summaryLength = 15
pluralizelisttitles = false

[Author]
  name = "Lane Wagner"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'

[taxonomies]
  category = "categories"

[permalinks]
  post = "/:section/:slug/"
  categories = "/:slug/"

[params]
  description = "You don't need a CS degree to get hired, but you do need computer science skills. Prepare to land an entry-level role in tech by building real coding projects."
  footer = "&copy; [Boot.dev](https://boot.dev) {Year}"
  logo = "/favicons/favicon-32x32.png"
  googleTagManager = "GTM-PT7FHFB"
  dofollows = [
    "https://boot.dev",
    "https://blog.boot.dev",
    "https://wagslane.dev",
    "https://scrimba.com",
    "https://prepcards.dev"
  ]

  [[params.courses]]
    name = "Learn Python"
    type = "Course"
    link = "https://boot.dev/learn/learn-python"
    imgURL = "https://richstone.github.io/assets/images/logos/python-logo-small.png"
  [[params.courses]]
    name = "Learn Object Oriented Programming"
    type = "Course"
    link = "https://boot.dev/learn/learn-object-oriented-programming"
    imgURL = "https://richstone.github.io/assets/images/logos/python-logo-small.png"
  [[params.courses]]
    name = "Build a Local Dev Environment"
    type = "Project"
    link = "https://boot.dev/build/build-local-dev-environment-python"
    imgURL = "https://richstone.github.io/assets/images/logos/python-logo-small.png"
  [[params.courses]]
    name = "Learn Algorithms"
    type = "Course"
    link = "https://boot.dev/learn/learn-algorithms"
    imgURL = "https://richstone.github.io/assets/images/logos/python-logo-small.png"
  [[params.courses]]
    name = "Learn Data Structures"
    type = "Course"
    link = "https://boot.dev/learn/learn-data-structures"
    imgURL = "https://richstone.github.io/assets/images/logos/python-logo-small.png"
  [[params.courses]]
    name = "Build a Maze Solver"
    type = "Project"
    link = "https://boot.dev/build/maze-solver-python"
    imgURL = "https://richstone.github.io/assets/images/logos/python-logo-small.png"
  [[params.courses]]
    name = "Learn JavaScript"
    type = "Course"
    link = "https://boot.dev/learn/learn-javascript"
    imgURL = "https://cdn.iconscout.com/icon/free/png-256/javascript-2752148-2284965.png"
  [[params.courses]]
    name = "Learn HTTP"
    type = "Course"
    link = "https://boot.dev/learn/learn-http"
    imgURL = "https://cdn.iconscout.com/icon/free/png-256/javascript-2752148-2284965.png"
  [[params.courses]]
    name = "Build a Link Analyzer"
    type = "Project"
    link = "https://boot.dev/build/link-analyzer"
    imgURL = "https://cdn.iconscout.com/icon/free/png-256/javascript-2752148-2284965.png"
  [[params.courses]]
    name = "Learn Functional Programming"
    type = "Course"
    link = "https://boot.dev/learn/learn-functional-programming"
    imgURL = "https://cdn.iconscout.com/icon/free/png-256/javascript-2752148-2284965.png"
  [[params.courses]]
    name = "Learn Go"
    type = "Course"
    link = "https://boot.dev/learn/learn-golang"
    imgURL = "https://user-images.githubusercontent.com/19890545/150690287-d7a7a4c0-ce89-4c49-8043-5af0348e615e.png"
  [[params.courses]]
    name = "Build a Social Media Back-end"
    type = "Project"
    link = "https://boot.dev/build/social-media-backend-golang"
    imgURL = "https://user-images.githubusercontent.com/19890545/150690287-d7a7a4c0-ce89-4c49-8043-5af0348e615e.png"
  [[params.courses]]
    name = "Learn SQL"
    type = "Course"
    link = "https://boot.dev/learn/learn-sql"
    imgURL = "https://i.imgur.com/TDs5Gpg.png"
  [[params.courses]]
    name = "Learn Cryptography"
    type = "Course"
    link = "https://boot.dev/learn/learn-cryptography"
    imgURL = "https://user-images.githubusercontent.com/19890545/150690287-d7a7a4c0-ce89-4c49-8043-5af0348e615e.png"
  [[params.courses]]
    name = "Learn Advanced Algorithms"
    type = "Course"
    link = "https://boot.dev/learn/learn-advanced-algorithms"
    imgURL = "https://richstone.github.io/assets/images/logos/python-logo-small.png"
  [[params.courses]]
    name = "Capstone Project"
    type = "Project"
    link = "https://boot.dev/build/capstone-project"
    imgURL = "https://cdn.iconscout.com/icon/free/png-256/code-280-460136.png"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "hugo gen chromastyles --style=dracula > assets/css/syntax.css"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'categories'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
